description: 'Workshop at KI2021: 44th German Conference on Artificial Intelligence'
date: 'September 27, 2021'
show_downloads: False
google_analytics:
theme: jekyll-theme-cayman
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
